version: '3'
services:
  # python3:
  #   build: ./fastapi
  #   container_name: 'fastapi'
  #   volumes:
  #     - ./fastapi:/root/fastapi
  #   ports:
  #     - 8000:8080
  # streamlit:
  #   build: ./streamlit
  #   container_name: 'streamlit'
  #   volumes:
  #     - ./streamlit:/root/streamlit
  #   ports:
  #     - 8501:8501
  app:
    build: ./app
    container_name: 'app'
    volumes:
      - ./app:/root/app
    ports:
      - 8000:8080
      - 8080:8501